### PR TITLE
AEROGEAR-3564 - use #nochrome link to hide navbar on docs

### PR DESCRIPTION
**Pull request by jasonmadigan**
See also: https://github.com/aerogear/antora-ui/pull/13

### CODE REVIEW

**Comment by ziccardi** [comment]
@jasonmadigan I don't see any difference in the running application after applying the change.
Here is how it appears on iOS (same on android):
screen shot 2018-07-02 at 15 00 28
.

**Comment by jasonmadigan** [comment]
@ziccardi sorry, should've mentioned - waiting for https://github.com/aerogear/antora-ui/pull/11 to be deployed to docs.aerogear.org - change will become visible then (I hope!)

**Comment by jasonmadigan** [comment]
@laurafitzgerald @ziccardi  changes enabling this to be tested in aerogear/antora-ui#13 have been landed. Should be OK to do a quick test now?

**Comment by laurafitzgerald** [comment]
@ziccardi thanks for checking. were you able to check them all? The sso one was causing some problem earlier

**Comment by ziccardi** [comment]
@laurafitzgerald : my local branch still had the old changes with `nochrome`. I made another check. The SSO page starts like on the footer:
screen shot 2018-07-03 at 18 53 47

**Comment by wei-lee** [comment]
@ziccardi I ran this PR locally and it works for me. Do you mind checking it again?

**Pull request merged**
