### PR TITLE
Fixing header

### PR DESCRIPTION
**Pull request by secondsun**

### CODE REVIEW

**Comment by wei-lee** [comment]
@secondsun @wojta just a small thing, can we change the sub-title to be "aerogear.org"?

**Comment by secondsun** [comment]
@wei-lee changed.

**Comment by wei-lee** [comment]
@secondsun mind fixing the conflict so that we can merge it and show it for the sprint review?

**Comment by secondsun** [comment]
@wei-lee Done.  The Designer.cs files can be ignored because they are auto generated.

**Comment by secondsun** [comment]
@wei-lee NVM, turns out this file doesn't get rebuilt for... reasons.

**Pull request merged**
